### ISSUE TITLE
Update breaks all

### ISSUE THREAD

**Issue by Lo263** [fclivaz42/42-nvim#2]
New istallation or update breaks all.
Issue may be hererocks

/////////////////////////////////////////////////////////////////////////////////////
    ○ hererocks 
        /home/loicr/.local/share/nvim/lazy/hererocks/hererocks.py:585: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
          archive.extractall(temp_dir)
        lauxlib.c: In function ‘luaL_loadfile’:
        lauxlib.c:577:4: warning: this ‘while’ clause does not guard... [-Wmisleading-indentation]
          577 |    while ((c = getc(lf.f)) != EOF && c != LUA_SIGNATURE[0]) ;
              |    ^~~~~
        lauxlib.c:578:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘while’
          578 |     lf.extraline = 0;
              |     ^~
        ldebug.c: In function ‘symbexec’:
        ldebug.c:268:36: warning: this statement may fall through [-Wimplicit-fallthrough=]
          268 | #define check(x)                if (!(x)) return 0;
              |                                    ^
        ldebug.c:272:33: note: in expansion of macro ‘check’
          272 | #define checkreg(pt,reg)        check((reg) < (pt)->maxstacksize)
              |                                 ^~~~~
        ldebug.c:414:9: note: in expansion of macro ‘checkreg’
          414 |         checkreg(pt, a+3);
              |         ^~~~~~~~
        ldebug.c:416:7: note: here
          416 |       case OP_JMP: {
              |       ^~~~
        ldump.c: In function ‘DumpString’:
        ldump.c:63:26: warning: the comparison will always evaluate as ‘false’ for the pointer operand in ‘s + 24’ must not be NULL [-Waddress]
           63 |  if (s==NULL || getstr(s)==NULL)
              |                          ^~
        llex.c: In function ‘llex’:
        llex.c:369:14: warning: this statement may fall through [-Wimplicit-fallthrough=]
          369 |         else luaX_lexerror(ls, "invalid long string delimiter", TK_STRING);
              |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        llex.c:371:7: note: here
          371 |       case '=': {
              |       ^~~~
        ltable.c: In function ‘luaH_get’:
        ltable.c:473:23: warning: this statement may fall through [-Wimplicit-fallthrough=]
          473 |     case LUA_TNUMBER: {
              |                       ^
        ltable.c:481:5: note: here
          481 |     default: {
              |     ^~~~~~~
        ltablib.c: In function ‘addfield’:
        ltablib.c:137:3: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
          137 |   if (!lua_isstring(L, -1))
              |   ^~
        ltablib.c:140:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
          140 |     luaL_addvalue(b);
              |     ^~~~~~~~~~~~~
        In file included from lua.h:16,
                         from lua.c:15:
        luaconf.h:275:10: fatal error: readline/readline.h: No such file or directory
          275 | #include <readline/readline.h>
              |          ^~~~~~~~~~~~~~~~~~~~~
        compilation terminated.
        Fetching Lua 5.1.5 from https://www.lua.org/ftp/lua-5.1.5.tar.gz
        Verifying SHA256 checksum
        Building Lua 5.1.5
        Skipping 1 patch, use --patch to apply it
        Running gcc -O2 -Wall -Wextra -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE -c -o lapi.o lapi.c
        Running gcc -O2 -Wall -Wextra -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE -c -o lauxlib.o lauxlib.c
        Running gcc -O2 -Wall -Wextra -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE -c -o lbaselib.o lbaselib.c
        Running gcc -O2 -Wall -Wextra -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE -c -o lcode.o lcode.c
        Running gcc -O2 -Wall -Wextra -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE -c -o ldblib.o ldblib.c
        Running gcc -O2 -Wall -Wextra -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE -c -o ldebug.o ldebug.c
        Running gcc -O2 -Wall -Wextra -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE -c -o ldo.o ldo.c
        Running gcc -O2 -Wall -Wextra -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE -c -o ldump.o ldump.c
        Running gcc -O2 -Wall -Wextra -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE -c -o lfunc.o lfunc.c
        Running gcc -O2 -Wall -Wextra -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE -c -o lgc.o lgc.c
        Running gcc -O2 -Wall -Wextra -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE -c -o linit.o linit.c
        Running gcc -O2 -Wall -Wextra -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE -c -o liolib.o liolib.c
        Running gcc -O2 -Wall -Wextra -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE -c -o llex.o llex.c
        Running gcc -O2 -Wall -Wextra -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE -c -o lmathlib.o lmathlib.c
        Running gcc -O2 -Wall -Wextra -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE -c -o lmem.o lmem.c
        Running gcc -O2 -Wall -Wextra -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE -c -o loadlib.o loadlib.c
        Running gcc -O2 -Wall -Wextra -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE -c -o lobject.o lobject.c
        Running gcc -O2 -Wall -Wextra -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE -c -o lopcodes.o lopcodes.c
        Running gcc -O2 -Wall -Wextra -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE -c -o loslib.o loslib.c
        Running gcc -O2 -Wall -Wextra -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE -c -o lparser.o lparser.c
        Running gcc -O2 -Wall -Wextra -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE -c -o lstate.o lstate.c
        Running gcc -O2 -Wall -Wextra -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE -c -o lstring.o lstring.c
        Running gcc -O2 -Wall -Wextra -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE -c -o lstrlib.o lstrlib.c
        Running gcc -O2 -Wall -Wextra -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE -c -o ltable.o ltable.c
        Running gcc -O2 -Wall -Wextra -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE -c -o ltablib.o ltablib.c
        Running gcc -O2 -Wall -Wextra -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE -c -o ltm.o ltm.c
        Running gcc -O2 -Wall -Wextra -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE -c -o lua.o lua.c
        Error: got exitcode 1 from command gcc -O2 -Wall -Wextra -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE -c -o lua.o lua.c
    ● image.nvim 0.26ms  neo-tree.nvim
        `/home/loicr/.local/share/nvim/lazy-rocks/hererocks/bin/lua` version `5.1` not installed

        This plugin requires `luarocks`. Try one of the following:
         - fix your `luarocks` installation
         - disable *hererocks* with `opts.rocks.hererocks = false`
         - disable `luarocks` support completely with `opts.rocks.enabled = false`

        Will try building anyway, but will likely fail...

        --------------------------------------------------------------------------------

        Failed to spawn process luarocks {
          args = { "--tree", "/home/loicr/.local/share/nvim/lazy-rocks/image.nvim", "--server", "https://nvim-neorocks.github.io/rocks-binaries/", "--lua-version", "5.1", "install", "--force-fast", "--deps-mode", "one", "image.nvim" },
          cwd = "/home/loicr/.local/share/nvim/lazy/image.nvim",
          env = {
            PATH = "/home/loicr/.local/share/nvim/lazy-rocks/hererocks/bin:/home/loicr/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/loicr/.local/bin:/home/loicr/.local/bin"
          },
          on_line = <function 1>,
          timeout = 120000
        }
        Failed installing image.nvim with `luarocks`.

        --------------------------------------------------------------------------------

        Trying to build from source.
        Failed to spawn process luarocks {
          args = { "--tree", "/home/loicr/.local/share/nvim/lazy-rocks/image.nvim", "--dev", "--lua-version", "5.1", "make", "--force-fast", "--deps-mode", "one" },
          cwd = "/home/loicr/.local/share/nvim/lazy/image.nvim",
          env = {
            PATH = "/home/loicr/.local/share/nvim/lazy-rocks/hererocks/bin:/home/loicr/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/loicr/.local/bin:/home/loicr/.local/bin"
          },
          on_line = <function 1>,
          timeout = 120000
        }
        
////////////////////////////////////////////////////////////////////////////////////
        THIS IS PART OF THE ISSUE
        
        
        Or maybe the luarocks is not here.

I dont really know.

**Comment by Lo263** [comment]
It works fine but when I did nvim -> u -> this happend

**Comment by Lo263** [comment]
Error detected while processing BufNewFile Autocommands for "*":                                                                                                                                                                                                
Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:36: BufNewFile Autocommands for "*"..FileType Autocommands for "*"..function <SNR>1_LoadFTPlugin[20]..script /home/lorey/.local/share/nvim/lazy/indent-blankline.nvim/after/ftplugin/c.lua: V
im(runtime):E5113: Error while calling lua chunk: .../share/nvim/lazy/indent-blankline.nvim/lua/ibl/utils.lua:22: type: expected function: 0x40c75308, got string (SKIP_LINE)                                                                                   
stack traceback:                                                                                                                                                                                                                                                
        [C]: in function 'error'                                                                                                                                                                                                                                
        vim/shared.lua: in function 'validate'                                                                                                                                                                                                                  
        .../share/nvim/lazy/indent-blankline.nvim/lua/ibl/utils.lua:22: in function 'validate'                                                                                                                                                                  
        .../share/nvim/lazy/indent-blankline.nvim/lua/ibl/hooks.lua:61: in function 'register'                                                                                                                                                                  
        ...are/nvim/lazy/indent-blankline.nvim/after/ftplugin/c.lua:3: in main chunk                                                                                                                                                                            
        [C]: in function 'nvim_cmd'                                                                                                                                                                                                                             
        /usr/share/nvim/runtime/filetype.lua:36: in function </usr/share/nvim/runtime/filetype.lua:35>                                                                                                                                                          
        [C]: in function 'pcall'                                                                                                                                                                                                                                
        vim/shared.lua: in function <vim/shared.lua:0>                                                                                                                                                                                                          
        [C]: in function '_with'                                                                                                                                                                                                                                
        /usr/share/nvim/runtime/filetype.lua:35: in function </usr/share/nvim/runtime/filetype.lua:10>                                                                                                                                                          
stack traceback:                                                                                                                                                                                                                                                
        [C]: in function '_with'                                                                                                                                                                                                                                
        /usr/share/nvim/runtime/filetype.lua:35: in function </usr/share/nvim/runtime/filetype.lua:10>

**Comment by doublegras** [comment]
Same problem here, apt install luarocks fix the issue, but wiithout root privilege cannot figure out how to solve the issue

**Comment by fclivaz42** [comment]
branch "testing" has a fix available, would you mind checking out if it works better? @doublegras @Lo263 

i changed image.nvim's config from magick_ocks to magick_cli which should prevent this issue. Let me know if it works and i'll merge it in main :)

**Comment by fclivaz42** [comment]
> Error detected while processing BufNewFile Autocommands for "_": Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:36: BufNewFile Autocommands for "_"..FileType Autocommands for "*"..function 1_LoadFTPlugin[20]..script /home/lorey/.local/share/nvim/lazy/indent-blankline.nvim/after/ftplugin/c.lua: V im(runtime):E5113: Error while calling lua chunk: .../share/nvim/lazy/indent-blankline.nvim/lua/ibl/utils.lua:22: type: expected function: 0x40c75308, got string (SKIP_LINE) stack traceback: [C]: in function 'error' vim/shared.lua: in function 'validate' .../share/nvim/lazy/indent-blankline.nvim/lua/ibl/utils.lua:22: in function 'validate' .../share/nvim/lazy/indent-blankline.nvim/lua/ibl/hooks.lua:61: in function 'register' ...are/nvim/lazy/indent-blankline.nvim/after/ftplugin/c.lua:3: in main chunk [C]: in function 'nvim_cmd' /usr/share/nvim/runtime/filetype.lua:36: in function </usr/share/nvim/runtime/filetype.lua:35> [C]: in function 'pcall' vim/shared.lua: in function <vim/shared.lua:0> [C]: in function '_with' /usr/share/nvim/runtime/filetype.lua:35: in function </usr/share/nvim/runtime/filetype.lua:10> stack traceback: [C]: in function '_with' /usr/share/nvim/runtime/filetype.lua:35: in function </usr/share/nvim/runtime/filetype.lua:10>

I unfortunately don't think I can fix this as this seems to be an upstream issue with indent-blankline and not 42-nvim. you can safely ignore that

**Comment by fclivaz42** [comment]
"Patched" the luarocks issue in the [V1.3](https://github.com/fclivaz42/42-nvim/releases/tag/V1.3) release!

When it comes to indent-blankline crashing, it's (from what I have seen) because you are using a nightly devbuild of neovim. So unfortunately cannot fix here :(

(edit: typos)
